package dev.slne.surf.premium.shop.utils

import dev.slne.surf.surfapi.bukkit.api.permission.PermissionRegistry

object PermissionRegistry : PermissionRegistry() {
    private const val PREFIX = "surf.premium.shop"
    private const val COMMAND_PREFIX = "$PREFIX.command"

    val COMMAND_BASE = "$COMMAND_PREFIX.base"
    val COMMAND_ENABLED_STATE = "$COMMAND_PREFIX.enabled"
    val COMMAND_RELOAD = "$COMMAND_PREFIX.reload"
    val COMMAND_OPEN = "$COMMAND_PREFIX.open"

    private const val COMMAND_FURNITURE_PREFIX = "$COMMAND_PREFIX.furniture"
    val COMMAND_FURNITURE_BASE = "$COMMAND_FURNITURE_PREFIX.base"

    private const val COMMAND_FURNITURE_CATEGORY_PREFIX = "$COMMAND_FURNITURE_PREFIX.category"
    val COMMAND_FURNITURE_CATEGORY_BASE = "$COMMAND_FURNITURE_CATEGORY_PREFIX.base"
    val COMMAND_FURNITURE_CATEGORY_LIST = "$COMMAND_FURNITURE_CATEGORY_PREFIX.list"
    val COMMAND_FURNITURE_CATEGORY_INFO = "$COMMAND_FURNITURE_CATEGORY_PREFIX.info"
    val COMMAND_FURNITURE_CATEGORY_CREATE = "$COMMAND_FURNITURE_CATEGORY_PREFIX.create"
    val COMMAND_FURNITURE_CATEGORY_DELETE = "$COMMAND_FURNITURE_CATEGORY_PREFIX.delete"
    val COMMAND_FURNITURE_CATEGORY_ADD_ITEM = "$COMMAND_FURNITURE_CATEGORY_PREFIX.add-item"
    val COMMAND_FURNITURE_CATGEORY_REMOVE_ITEM = "$COMMAND_FURNITURE_CATEGORY_PREFIX.remove-item"
}